# Generated by Django 2.2 on 2020-12-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_envio', '0002_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=15, verbose_name=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')]),
        ),
    ]
