# Generated by Django 2.2 on 2021-01-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_envio', '0003_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion_envio.DireccionEnvio', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
    ]
