# Generated by Django 2.2 on 2021-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_envio', '0004_auto_20210108_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='telefono',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
