# Generated by Django 2.2 on 2021-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion_envio', '0005_direccionenvio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pago',
            field=models.ImageField(blank=True, null=True, upload_to='Pagos/'),
        ),
    ]
