# Generated by Django 2.2 on 2020-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_auto_20201216_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('correo1', models.EmailField(max_length=254, verbose_name='Correo 1')),
                ('correo2', models.EmailField(max_length=254, verbose_name='Correo 2')),
                ('telefono1', models.CharField(max_length=10, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(max_length=10, verbose_name='Telefono 2')),
                ('mapa', models.URLField(max_length=300, verbose_name='Mapa')),
                ('facebbok', models.URLField(max_length=300, verbose_name='Facebook')),
                ('whatsapp', models.URLField(max_length=300, verbose_name='WhatsApp')),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('disponibilidad', models.CharField(choices=[('1', 'Disponible'), ('2', 'No disponible')], max_length=1, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(upload_to='Productos/', verbose_name='Productos')),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
