# Generated by Django 2.2 on 2020-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0003_contacto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mapa',
            field=models.TextField(verbose_name='Mapa'),
        ),
    ]
