# Generated by Django 2.2 on 2021-01-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_auto_20201216_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='imagen3',
        ),
    ]
